services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hf-db
    platform: linux/amd64
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'HF123456!'
    ports:
      - '1434:1433'
    volumes:
      - hf-db-data:/var/opt/mssql

volumes:
  hf-db-data:
